### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by eonist** [leoMehlig/SwiftEnigma#1]
Hey: 

Do you know how to use Range generics in swift 3?

```swift
Range where Element:Comparable
```

https://github.com/leoMehlig/SwiftEnigma/blob/4eea41b939188f10fee4fff098a5695e8bb34b8c/Enigma/Range.swift

**Comment by leoMehlig** [comment]
I need to change this to `CountableRange`. 

Stil need to do the conversion to swift 3 ;)

**Comment by eonist** [comment]
Yeah, Im in the middle of migration. 

I can't figure out Range + Extension + Generics

And very little information on the internet.

**Comment by leoMehlig** [comment]
```
extension CountableRange where Bound: Comparable {
    func inBounds(index: Bound) -> Bound {
        if index < self.startIndex {
            return self.inBounds(index: index.advanced(by: self.count+1))
        } else if index >= self.endIndex {
            return self.inBounds(index: index.advanced(by: -(self.count-1)))
        }
        return index
    }
}
```

This should work 😉

**Comment by eonist** [comment]
Just figured it out last night I didn't get that Element is now called Bound. Going from swift 2 -> swift 3. Thanks!

**Comment by eonist** [comment]
Made a swift migration blog post: http://stylekit.org/blog/2017/01/12/swift-3-migration/
